// TM-43: Coaching Matrix baseline, transcribed from Andy's
// SJJ_Coaching_Matrix.xlsx exactly as provided (2026-09-23), covering every
// head-coach season through 2026. Opponent names are kept as written in
// the spreadsheet; the page canonicalizes them through the opponent
// lookup at render time so they merge with live games.
//
// Everything from the first auto_record season on (2027+) is calculated
// live from imported game results instead (src/lib/coachingMatrix.js).
// Seasons before that are covered by this baseline, and ONLY by it, so
// no game is ever counted twice.
//
// Coaches before Mike McComish (Jim Reed, Chad Fredericks, Mike Degens,
// Brad Lay) have no opponent-level detail in the source, so they have
// no rows here.
//
// Row shape: [head coach, opponent, regular W, regular L, playoff W, playoff L]
export const COACHING_MATRIX_BASELINE = [
  ["Andrew Smith", "Anthony Wayne", 4, 0, 0, 0],
  ["Andrew Smith", "Archbishop Hoban", 1, 0, 0, 0],
  ["Andrew Smith", "Bay", 3, 0, 0, 0],
  ["Andrew Smith", "Benedictine", 0, 0, 3, 0],
  ["Andrew Smith", "Bishop Watterson", 0, 2, 0, 0],
  ["Andrew Smith", "Bowling Green", 2, 0, 0, 0],
  ["Andrew Smith", "Brebeuf Jesuit", 1, 0, 0, 0],
  ["Andrew Smith", "Brother Rice", 0, 3, 0, 0],
  ["Andrew Smith", "Chagrin Falls", 1, 0, 0, 1],
  ["Andrew Smith", "Chaminade Julienne", 1, 1, 0, 0],
  ["Andrew Smith", "Columbus Academy", 1, 0, 0, 0],
  ["Andrew Smith", "Copley", 0, 1, 0, 0],
  ["Andrew Smith", "Cranbrook", 3, 1, 0, 0],
  ["Andrew Smith", "CVCA", 1, 0, 0, 0],
  ["Andrew Smith", "De La Salle", 3, 0, 0, 0],
  ["Andrew Smith", "Detroit Catholic Central", 0, 3, 0, 0],
  ["Andrew Smith", "Detroit Country Day", 0, 2, 0, 0],
  ["Andrew Smith", "Eugene Ashley (NC)", 0, 1, 0, 0],
  ["Andrew Smith", "Findlay", 1, 0, 0, 0],
  ["Andrew Smith", "Gilmour Academy", 1, 0, 0, 0],
  ["Andrew Smith", "Holy Name", 0, 0, 1, 0],
  ["Andrew Smith", "Indian Hill", 0, 1, 0, 0],
  ["Andrew Smith", "Lincoln Gahanna", 1, 0, 0, 0],
  ["Andrew Smith", "Northview", 4, 0, 0, 0],
  ["Andrew Smith", "Oakwood", 2, 0, 0, 0],
  ["Andrew Smith", "Olmsted Falls", 2, 1, 0, 1],
  ["Andrew Smith", "Orchard Lake St. Mary's", 2, 2, 0, 0],
  ["Andrew Smith", "Ottawa Hills", 4, 2, 4, 0],
  ["Andrew Smith", "Padua Franciscan", 0, 0, 1, 0],
  ["Andrew Smith", "Perrysburg", 4, 1, 0, 0],
  ["Andrew Smith", "Revere", 1, 0, 0, 0],
  ["Andrew Smith", "Rocky River", 0, 1, 2, 1],
  ["Andrew Smith", "Shaker Heights", 0, 1, 0, 0],
  ["Andrew Smith", "Southview", 5, 0, 1, 0],
  ["Andrew Smith", "St. Edward's", 1, 1, 0, 0],
  ["Andrew Smith", "St. Francis Columbus", 0, 0, 0, 1],
  ["Andrew Smith", "St. Francis Toledo", 3, 3, 2, 2],
  ["Andrew Smith", "St. Ignatius Blue", 1, 1, 0, 0],
  ["Andrew Smith", "St. Joseph's", 1, 1, 0, 0],
  ["Andrew Smith", "Topsail (NC)", 1, 0, 0, 0],
  ["Andrew Smith", "UD Jesuit", 5, 0, 0, 0],
  ["Andrew Smith", "University School", 0, 0, 1, 0],
  ["Andrew Smith", "Walsh Jesuit", 2, 2, 1, 0],
  ["Andrew Smith", "Westlake", 4, 0, 0, 0],
  ["Andrew Smith", "Wooster", 0, 0, 1, 0],
  ["Adam Salon", "Ann Arbor Pioneer", 0, 2, 0, 0],
  ["Adam Salon", "Anthony Wayne", 2, 3, 0, 0],
  ["Adam Salon", "Archbishop Hoban", 0, 1, 0, 0],
  ["Adam Salon", "Avon", 1, 0, 0, 0],
  ["Adam Salon", "Avon Lake", 0, 0, 1, 0],
  ["Adam Salon", "Bay", 1, 0, 0, 0],
  ["Adam Salon", "Bowling Green", 2, 0, 0, 0],
  ["Adam Salon", "Brebeuf Jesuit", 2, 0, 0, 0],
  ["Adam Salon", "Brecksville Broadview", 1, 0, 0, 0],
  ["Adam Salon", "Brunswick", 3, 0, 1, 0],
  ["Adam Salon", "Chagrin Falls", 0, 1, 0, 0],
  ["Adam Salon", "Delaware Hayes", 0, 2, 0, 1],
  ["Adam Salon", "Erie McDowell", 1, 0, 0, 0],
  ["Adam Salon", "Fishers", 0, 1, 0, 0],
  ["Adam Salon", "Hilliard Darby", 0, 1, 0, 0],
  ["Adam Salon", "Kenston", 0, 1, 0, 0],
  ["Adam Salon", "Lincoln, Gahanna", 1, 0, 0, 0],
  ["Adam Salon", "Marquette", 1, 1, 0, 0],
  ["Adam Salon", "Massilon Jackson", 1, 2, 0, 0],
  ["Adam Salon", "Medina", 1, 1, 0, 0],
  ["Adam Salon", "Mentor", 0, 2, 0, 0],
  ["Adam Salon", "Olentangy", 0, 0, 0, 1],
  ["Adam Salon", "Ottawa Hills", 2, 2, 0, 1],
  ["Adam Salon", "Perrysburg", 4, 2, 1, 0],
  ["Adam Salon", "Rocky River", 0, 1, 0, 0],
  ["Adam Salon", "Saline", 0, 2, 0, 0],
  ["Adam Salon", "Shaker Heights", 1, 0, 0, 0],
  ["Adam Salon", "St. Charles", 0, 1, 0, 0],
  ["Adam Salon", "St. Edward", 0, 2, 0, 0],
  ["Adam Salon", "St. Francis Toledo", 0, 5, 0, 1],
  ["Adam Salon", "St. Ignatius (Prep)", 0, 1, 0, 1],
  ["Adam Salon", "Stow Monroe Falls", 1, 0, 0, 0],
  ["Adam Salon", "Strongsville", 3, 1, 0, 0],
  ["Adam Salon", "Summit Country Day", 1, 0, 0, 0],
  ["Adam Salon", "Sylvania Northview", 5, 0, 0, 0],
  ["Adam Salon", "Sylvania Southview", 5, 0, 1, 0],
  ["Adam Salon", "Toledo Central Catholic", 2, 0, 0, 0],
  ["Adam Salon", "University of Detroit Jesuit", 0, 1, 0, 0],
  ["Adam Salon", "Wadsworth", 3, 0, 0, 0],
  ["Adam Salon", "Westlake", 2, 0, 1, 0],
  ["Adam Salon", "Wooster", 1, 1, 0, 0],
  ["Mike McComish", "Ann Arbor Pioneer", 0, 3, 0, 0],
  ["Mike McComish", "Ann Arbor Skyline", 1, 1, 0, 0],
  ["Mike McComish", "Anthony Wayne", 4, 0, 0, 0],
  ["Mike McComish", "Bedford", 1, 0, 0, 0],
  ["Mike McComish", "Bishop Watterson", 1, 1, 0, 0],
  ["Mike McComish", "Brebeuf Jesuit", 2, 0, 0, 0],
  ["Mike McComish", "Brother Rice (Orange)", 0, 1, 0, 0],
  ["Mike McComish", "Brunswick", 0, 0, 1, 0],
  ["Mike McComish", "Cathedral Prep", 1, 0, 0, 0],
  ["Mike McComish", "Cincinnati St. Xavier", 1, 0, 0, 0],
  ["Mike McComish", "Clarkston", 1, 0, 0, 0],
  ["Mike McComish", "DeSmet Jesuit", 1, 0, 0, 0],
  ["Mike McComish", "Detroit Catholic Central", 2, 1, 0, 0],
  ["Mike McComish", "Dublin Coffman", 2, 1, 0, 1],
  ["Mike McComish", "Dublin Jerome", 0, 0, 0, 1],
  ["Mike McComish", "Erie McDowell", 2, 1, 0, 0],
  ["Mike McComish", "Hilliard Darby", 3, 0, 0, 0],
  ["Mike McComish", "Hilliard Davidson", 1, 0, 0, 0],
  ["Mike McComish", "Hoover", 1, 3, 0, 0],
  ["Mike McComish", "Hudson", 0, 2, 0, 0],
  ["Mike McComish", "Kent Roosevelt", 2, 2, 0, 0],
  ["Mike McComish", "Lakota West", 2, 0, 0, 0],
  ["Mike McComish", "Lexington Catholic", 1, 0, 0, 0],
  ["Mike McComish", "Lexington Dunbar", 1, 0, 0, 0],
  ["Mike McComish", "Lexington Tates Creek", 1, 0, 0, 0],
  ["Mike McComish", "Liberty Olentangy", 0, 1, 0, 0],
  ["Mike McComish", "Marquette", 2, 0, 0, 0],
  ["Mike McComish", "Massilon Jackson", 0, 1, 0, 0],
  ["Mike McComish", "Medina", 2, 6, 0, 0],
  ["Mike McComish", "Notre Dame Prep", 1, 2, 0, 0],
  ["Mike McComish", "Olentangy", 1, 6, 0, 0],
  ["Mike McComish", "Perrysburg", 8, 0, 1, 0],
  ["Mike McComish", "Seneca Valley", 0, 1, 0, 0],
  ["Mike McComish", "Shaker Heights", 1, 0, 0, 0],
  ["Mike McComish", "Solon", 0, 1, 0, 0],
  ["Mike McComish", "St. Charles", 1, 3, 0, 0],
  ["Mike McComish", "St. Edward", 0, 0, 0, 1],
  ["Mike McComish", "St. Francis Toledo", 6, 5, 0, 0],
  ["Mike McComish", "St. Ignatius (Prep)", 1, 6, 0, 0],
  ["Mike McComish", "Strongsville", 0, 1, 0, 1],
  ["Mike McComish", "Summit Country Day", 0, 1, 0, 0],
  ["Mike McComish", "Sylvania Maple Leafs", 3, 2, 0, 0],
  ["Mike McComish", "Sylvania Northview", 4, 0, 1, 0],
  ["Mike McComish", "Sylvania Southview", 0, 6, 0, 2],
  ["Mike McComish", "Thomas Worthington", 0, 2, 0, 2],
  ["Mike McComish", "Toledo Central Catholic", 5, 0, 0, 0],
  ["Mike McComish", "Troy Athens", 0, 2, 0, 0],
  ["Mike McComish", "University School", 0, 1, 0, 0],
  ["Mike McComish", "Upper Arlington", 0, 3, 0, 0],
  ["Mike McComish", "Walsh Jesuit", 2, 0, 0, 0],
  ["Mike McComish", "Westerville North", 2, 0, 1, 0],
  ["Mike McComish", "Westlake", 0, 0, 1, 0],
  ["Mike McComish", "Wheeling Cent Cath", 1, 0, 0, 0],
  ["Mike McComish", "Wooster", 0, 1, 0, 0],
];
