-- Coaching staff history import, generated by scripts/staffCsvToSql.py
-- from sjj_coaching_staff_template.csv (27 rows). Adds new people to staff and
-- new season roles to staff_seasons. Anything already on file is
-- skipped, never changed or duplicated.

BEGIN;

-- Temporary staging table, gone when the session ends.
CREATE TEMP TABLE staff_import (
  first_name TEXT, last_name TEXT, first_year INT, last_year INT, team_level TEXT, role TEXT
);

INSERT INTO staff_import VALUES
  ('Eric', 'Fraeyman', 2026, 2026, 'Varsity', 'Assistant'),
  ('Eric', 'Brown', 2015, 2019, 'Varsity', 'Box Coach'),
  ('Eric', 'Brown', 2021, 2027, 'Varsity', 'Box Coach'),
  ('Eric', 'Brown', 2015, 2019, 'JV Gold', 'Head Coach'),
  ('Eric', 'Brown', 2021, 2027, 'JV Gold', 'Head Coach'),
  ('Ross', 'Mellgren', 2023, 2027, 'Varsity', 'Defensive Coordinator'),
  ('Brad', 'Scheuermann', 2022, 2027, 'Varsity', 'Defensive Assistant/Goalie Coach'),
  ('Tanner', 'Gil-Snow', 2025, 2026, 'Varsity', 'Offensive Assistant'),
  ('Gage', 'Knapp', 2022, 2027, 'JV Gold', 'Assistant'),
  ('Steven', 'Speer', 2021, 2025, 'JV Gold', 'Assistant'),
  ('Renzo', 'Cordero', 2020, 2027, 'JV Gold', 'Assistant'),
  ('Gage', 'Knapp', 2025, 2025, 'JV Blue', 'Assistant'),
  ('Steven', 'Speer', 2025, 2025, 'JV Blue', 'Assistant'),
  ('Renzo', 'Cordero', 2025, 2025, 'JV Blue', 'Head Coach'),
  ('Nate', 'Miller', 2020, 2020, 'Varsity', 'Offensive Coordinator'),
  ('Nate', 'Miller', 2021, 2022, 'Varsity', 'Offensive Assistant'),
  ('Sam', 'Rodgers', 2024, 2024, 'Varsity', 'Defensive Assistant'),
  ('Jeff', 'Szozda', 2021, 2023, 'Varsity', 'Faceoff Coach'),
  ('Jeff', 'Szozda', 2021, 2023, 'JV Gold', 'Assistant'),
  ('Patrick', 'Alfano', 2021, 2021, 'Varsity', 'Offensive Assistant'),
  ('Rod', 'Miller', 2020, 2020, 'Varsity', 'Offensive Assistant'),
  ('Danny', 'McCartney', 2020, 2020, 'JV Gold', 'Assistant'),
  ('Ben', 'Uncapher', 2020, 2020, 'JV Gold', 'Assistant'),
  ('Ryan', 'Almester', 2020, 2020, 'JV Gold', 'Assistant'),
  ('Sean', 'Cordero', 2020, 2020, 'Varsity', 'Defensive Coordinator'),
  ('Christian', 'King', 2020, 2020, 'JV Gold', 'Assistant'),
  ('Jeff', 'Szozda', 2020, 2020, 'JV Gold', 'Head Coach');

-- Refuse to run if a new name is a near-duplicate of someone already on
-- staff (same last name and first three letters, not an exact match).
-- Fix the spelling in the CSV to match the site, or confirm they really
-- are different people, then regenerate.
DO $$
DECLARE conflicts TEXT;
BEGIN
  SELECT string_agg(DISTINCT i.first_name || ' ' || i.last_name || ' vs existing ' || s.first_name || ' ' || s.last_name, '; ')
  INTO conflicts
  FROM staff_import i
  JOIN staff s ON s.team_id = (SELECT id FROM teams WHERE slug = 'sjj')
    AND lower(s.last_name) = lower(i.last_name)
    AND lower(left(s.first_name, 3)) = lower(left(i.first_name, 3))
    AND lower(s.first_name) <> lower(i.first_name);
  IF conflicts IS NOT NULL THEN
    RAISE EXCEPTION 'Possible duplicate people, nothing imported: %', conflicts;
  END IF;
END $$;

INSERT INTO staff (team_id, first_name, last_name)
SELECT DISTINCT (SELECT id FROM teams WHERE slug = 'sjj'), i.first_name, i.last_name
FROM staff_import i
WHERE NOT EXISTS (
  SELECT 1 FROM staff s
  WHERE s.team_id = (SELECT id FROM teams WHERE slug = 'sjj')
    AND lower(s.first_name) = lower(i.first_name) AND lower(s.last_name) = lower(i.last_name)
);

INSERT INTO staff_seasons (staff_id, season_year, team_level, role)
SELECT s.id, y.season_year, i.team_level, i.role
FROM staff_import i
CROSS JOIN LATERAL generate_series(i.first_year, i.last_year) AS y(season_year)
JOIN staff s ON s.team_id = (SELECT id FROM teams WHERE slug = 'sjj')
  AND lower(s.first_name) = lower(i.first_name) AND lower(s.last_name) = lower(i.last_name)
ON CONFLICT (staff_id, season_year, team_level, role) DO NOTHING;

COMMIT;

-- Verify: each imported person, their seasons on file, and their roles.
SELECT s.first_name, s.last_name, COUNT(DISTINCT ss.season_year) AS seasons,
       MIN(ss.season_year) AS first_year, MAX(ss.season_year) AS last_year,
       string_agg(DISTINCT ss.team_level || ' ' || ss.role, ', ') AS roles
FROM staff s JOIN staff_seasons ss ON ss.staff_id = s.id
WHERE s.team_id = (SELECT id FROM teams WHERE slug = 'sjj')
  AND (lower(s.first_name), lower(s.last_name)) IN (
    SELECT DISTINCT lower(first_name), lower(last_name) FROM staff_import)
GROUP BY s.first_name, s.last_name
ORDER BY seasons DESC, s.last_name;
