"""Turn a filled-in sjj_coaching_staff_template.csv into a db/0XX migration.

Usage: python3 scripts/staffCsvToSql.py input.csv db/0XX_name.sql

Columns: first_name,last_name,first_year,last_year,team_level,role
(last_year blank = single season). Whitespace is trimmed. The generated
SQL adds new staff and staff_seasons rows only, skipping anything
already on file, and refuses to run if a new name looks like a
near-duplicate of an existing staff member (same last name, same first
three letters of the first name, but not an exact match, e.g. "Nate"
vs "Nathan"), so a second copy of a real person is never created.
"""
import csv, sys

TEAM_LEVELS = ('Varsity', 'JV Gold', 'JV Blue')

def q(s):
    return "'" + s.replace("'", "''") + "'"

def main(src, dst):
    rows = []
    with open(src, newline='', encoding='utf-8-sig') as f:
        for i, r in enumerate(csv.DictReader(f), start=2):
            r = {k.strip(): (v or '').strip() for k, v in r.items() if k}
            if not any(r.values()):
                continue
            fy = int(r['first_year'])
            ly = int(r['last_year']) if r['last_year'] else fy
            if ly < fy or r['team_level'] not in TEAM_LEVELS or not r['role'] or not r['first_name'] or not r['last_name']:
                sys.exit(f'Bad row on line {i}: {r}')
            rows.append((r['first_name'], r['last_name'], fy, ly, r['team_level'], r['role']))

    values = ',\n  '.join(f'({q(a)}, {q(b)}, {fy}, {ly}, {q(lvl)}, {q(role)})' for a, b, fy, ly, lvl, role in rows)
    sql = f"""-- Coaching staff history import, generated by scripts/staffCsvToSql.py
-- from {src.split('/')[-1]} ({len(rows)} rows). Adds new people to staff and
-- new season roles to staff_seasons. Anything already on file is
-- skipped, never changed or duplicated.

BEGIN;

-- Temporary staging table, gone when the session ends.
CREATE TEMP TABLE staff_import (
  first_name TEXT, last_name TEXT, first_year INT, last_year INT, team_level TEXT, role TEXT
);

INSERT INTO staff_import VALUES
  {values};

-- Refuse to run if a new name is a near-duplicate of someone already on
-- staff (same last name and first three letters, not an exact match).
-- Fix the spelling in the CSV to match the site, or confirm they really
-- are different people, then regenerate.
DO $$
DECLARE conflicts TEXT;
BEGIN
  SELECT string_agg(DISTINCT i.first_name || ' ' || i.last_name || ' vs existing ' || s.first_name || ' ' || s.last_name, '; ')
  INTO conflicts
  FROM staff_import i
  JOIN staff s ON s.team_id = (SELECT id FROM teams WHERE slug = 'sjj')
    AND lower(s.last_name) = lower(i.last_name)
    AND lower(left(s.first_name, 3)) = lower(left(i.first_name, 3))
    AND lower(s.first_name) <> lower(i.first_name);
  IF conflicts IS NOT NULL THEN
    RAISE EXCEPTION 'Possible duplicate people, nothing imported: %', conflicts;
  END IF;
END $$;

INSERT INTO staff (team_id, first_name, last_name)
SELECT DISTINCT (SELECT id FROM teams WHERE slug = 'sjj'), i.first_name, i.last_name
FROM staff_import i
WHERE NOT EXISTS (
  SELECT 1 FROM staff s
  WHERE s.team_id = (SELECT id FROM teams WHERE slug = 'sjj')
    AND lower(s.first_name) = lower(i.first_name) AND lower(s.last_name) = lower(i.last_name)
);

INSERT INTO staff_seasons (staff_id, season_year, team_level, role)
SELECT s.id, y.season_year, i.team_level, i.role
FROM staff_import i
CROSS JOIN LATERAL generate_series(i.first_year, i.last_year) AS y(season_year)
JOIN staff s ON s.team_id = (SELECT id FROM teams WHERE slug = 'sjj')
  AND lower(s.first_name) = lower(i.first_name) AND lower(s.last_name) = lower(i.last_name)
ON CONFLICT (staff_id, season_year, team_level, role) DO NOTHING;

COMMIT;

-- Verify: each imported person, their seasons on file, and their roles.
SELECT s.first_name, s.last_name, COUNT(DISTINCT ss.season_year) AS seasons,
       MIN(ss.season_year) AS first_year, MAX(ss.season_year) AS last_year,
       string_agg(DISTINCT ss.team_level || ' ' || ss.role, ', ') AS roles
FROM staff s JOIN staff_seasons ss ON ss.staff_id = s.id
WHERE s.team_id = (SELECT id FROM teams WHERE slug = 'sjj')
  AND (lower(s.first_name), lower(s.last_name)) IN (
    SELECT DISTINCT lower(first_name), lower(last_name) FROM staff_import)
GROUP BY s.first_name, s.last_name
ORDER BY seasons DESC, s.last_name;
"""
    open(dst, 'w').write(sql)
    print(f'{len(rows)} rows -> {dst}')

if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
